echo '-------------------------------------'
echo '						     '
echo '						     '
echo '						     '
echo 'V. Phase Five' 
echo 'Remove Built Image from Local Machine'
echo '                                     '
echo '                                     '
echo '-------------------------------------'
docker rmi $registry:latest

echo '---------------------------------------------'
echo '						     			  '
echo '						     			  '
echo '						     			  '
echo '=============REMOVE COMPLETED============='
echo '						     			  '
echo '						     			  '
echo '---------------------------------------------'
